name: Turing_machine code OCaml

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: cd code/turing_machine && opam install . --deps-only

      - name: Build
        run: cd code/turing_machine && opam exec -- dune build

      - name: Test
        run: cd code/turing_machine && opam exec -- dune runtest

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Go to the OCaml code
        run: cd code/turing_machine

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: cd code/turing_machine && opam install . --deps-only

      - name: Build
        run: cd code/turing_machine && opam exec -- dune build

      - name: Install dune-format
        run: cd code/turing_machine && opam install ocamlformat

      - name: Format
        run: cd code/turing_machine && opam exec -- dune build @fmt --auto-promote
